<a href="https://colab.research.google.com/github/sumeet2-lab/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy
* Uniform data 
* we use due to list is slow

In [2]:
import numpy as np

In [3]:
arr= np.array([1,2,3])
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(arr.ndim)  #ndim ==> shows how much dimension it has

1


In [9]:
 arr.dtype

dtype('uint8')

In [10]:
arr =np.array([1,2,3],dtype="uint8")

In [8]:
arr.dtype

dtype('uint8')

In [11]:
arr1= np.array([1,2,3,4,56.3])
print(arr1.dtype)

float64


## Time

In [55]:
lst=[32]*1000
print(lst)
print(len(lst))

[32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,

In [54]:
arr2=np.ones(1000)
arr2=arr2*32
print(arr2)
print(len(arr2))

[32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.
 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32

In [24]:
%timeit sum(lst)   # sum(lst) use kiya for sum and this func is in python

1000 loops, best of 5: 744 µs per loop


In [25]:
%timeit arr2.sum()   # sum() use kiya so fast sum huya as arr2.sum() ==> functions of numpy

The slowest run took 4.43 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 37 µs per loop


In [26]:
%timeit sum(arr2)     # sum(arr2) use kiya for sum and this func is in python and yeh bahut bulky ho raha as seen in results compared to previous cell

100 loops, best of 5: 17.1 ms per loop




Numpy stands for numerical Python.

It is a library of python to work with Arrays

In [30]:
arr=np.ones((3,4),dtype="uint8")

In [32]:
arr.shape

(3, 4)

In [34]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [39]:
print(arr)

[   1    2 1000    4    5]


In [40]:
arr.shape

(5,)

# Slicing

numpy slicing is shallow copy python does deep copy
* shallow copy  ==> call by reference type , changing other place reflect change in original too
* deep copy ==> call by value type, changing other place doesnot reflect change in original as there are 2 copy created in list(Python)

In [35]:
arr = np.arange(5,25,2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


In [36]:
arr[2:5]

array([ 9, 11, 13])

Proof 

In [37]:
lst = [1,2,3,4,5]
lst2 = lst[2:4] 
print(lst)
print(lst2)
lst2[0] = 1000
print(lst)
print(lst2)

[1, 2, 3, 4, 5]
[3, 4]
[1, 2, 3, 4, 5]
[1000, 4]


In [38]:
arr = np.array([1,2,3,4,5])
arr2 = arr[2:4]
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[   1    2 1000    4    5]
[1000    4]


In [41]:
arr = np.array([1,2,3,4,5])
arr2 = arr[2:4].copy()    # this create a deep copy in numpy
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[1 2 3 4 5]
[1000    4]


## 2D Array


In [43]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
arr.ndim

2

In [45]:
arr.shape

(3, 3)

In [46]:
arr.size

9

In [47]:
arr[0,1]

2

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr[::-1,::-1]     # reverse of arr

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [51]:
arr = np.ones((2,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [52]:
arr.shape

(2, 3, 4)

In [53]:
arr.ndim

3